# MxNet - NdArray

http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html

In [1]:
import mxnet as mx
from mxnet import nd
mx.random.seed(1)

C:\Users\vchakki\Documents\anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py:46: DeprecationWarning: OpenSSL.rand is deprecated - you should use os.urandom instead
  import OpenSSL.SSL


Create a 2D array (also called a matrix) with 3 rows and 4 columns

In [2]:
x = nd.empty((3, 4))
print(x)


[[ -1.83585205e+01   7.79121946e-43   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   2.60641514e-42   0.00000000e+00]
 [  0.00000000e+00   1.01938858e-38   0.00000000e+00   0.00000000e+00]]
<NDArray 3x4 @cpu(0)>


Create 2D array with zeros

In [3]:
x = nd.zeros((3, 4))
print(x)


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 3x4 @cpu(0)>


In [4]:
x = nd.ones((3, 4))
x


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

Create arrays whose values are sampled randomly. In this snippet, we initialize with values drawn from a standard normal distribution with zero mean and unit variance.

In [5]:
y = nd.random_normal(0, 1, shape=(3, 4))
y


[[ 0.03629482 -0.49024424 -0.95017928  0.03751943]
 [-0.72984648 -2.04010558  1.48213089  1.04082799]
 [-0.45256865  0.31160429 -0.83673781 -0.78830057]]
<NDArray 3x4 @cpu(0)>

In [6]:
y.shape

(3, 4)

In [7]:
y.size

12

# Operations - Mathematical Operations

In [8]:
x + y


[[ 1.03629482  0.50975573  0.04982072  1.03751945]
 [ 0.27015352 -1.04010558  2.482131    2.04082799]
 [ 0.54743135  1.31160426  0.16326219  0.21169943]]
<NDArray 3x4 @cpu(0)>

In [9]:
x * y


[[ 0.03629482 -0.49024424 -0.95017928  0.03751943]
 [-0.72984648 -2.04010558  1.48213089  1.04082799]
 [-0.45256865  0.31160429 -0.83673781 -0.78830057]]
<NDArray 3x4 @cpu(0)>

In [10]:
nd.exp(y)


[[ 1.03696156  0.61247677  0.38667169  1.03823221]
 [ 0.48198298  0.13001499  4.40231657  2.83156061]
 [ 0.63599241  1.36561418  0.43312114  0.45461673]]
<NDArray 3x4 @cpu(0)>

In [11]:
nd.dot(x, y.T)


[[-1.36660922 -0.24699318 -1.76600266]
 [-1.36660922 -0.24699318 -1.76600266]
 [-1.36660922 -0.24699318 -1.76600266]]
<NDArray 3x3 @cpu(0)>

# In-place operations

If we write y = x + y, we will dereference the matrix that y used to point to and instead point it at the newly allocated memory. We demonstrate this with Python’s id() function, which gives us the exact address of the referenced object in memory. 

In [12]:
print('id(y): ', id(y))
y = y + x
print('id(y): ', id(y))

id(y):  2391404462992
id(y):  2391404465848


Performing in-place operations in MXNet is as below, we can assign the result of an operation to a previously allocated array with slice notation

In [13]:
print('id(y): ', id(y))
y[:] = y + x
print('id(y): ', id(y))

id(y):  2391404465848
id(y):  2391404465848


x+y here will still allocate a temporary buffer to store the result before copying it to y[:]. To make even better use of memory, we can directly invoke the underlying ndarray operation, in this case elemwise_add, avoiding temporary buffers. We do this by specifying the out keyword argument, which every ndarray operator supports

In [14]:
nd.elemwise_add(x, y, out = y)


[[ 3.03629494  2.50975561  2.04982066  3.03751945]
 [ 2.27015352  0.95989442  4.482131    4.04082775]
 [ 2.54743147  3.31160426  2.16326213  2.21169949]]
<NDArray 3x4 @cpu(0)>

In [15]:
print('id(x): ', id(x))
x += y
x
print('id(x): ', id(x))

id(x):  2391257240800
id(x):  2391257240800


# Slicing

In [17]:
x


[[ 4.03629494  3.50975561  3.04982066  4.03751945]
 [ 3.27015352  1.95989442  5.482131    5.04082775]
 [ 3.54743147  4.3116045   3.16326213  3.21169949]]
<NDArray 3x4 @cpu(0)>

In [18]:
x[1:3]


[[ 3.27015352  1.95989442  5.482131    5.04082775]
 [ 3.54743147  4.3116045   3.16326213  3.21169949]]
<NDArray 2x4 @cpu(0)>

In [19]:
x[1, 2] = 9.0
x


[[ 4.03629494  3.50975561  3.04982066  4.03751945]
 [ 3.27015352  1.95989442  9.          5.04082775]
 [ 3.54743147  4.3116045   3.16326213  3.21169949]]
<NDArray 3x4 @cpu(0)>

In [20]:
x[1:3, 1:2]


[[ 1.95989442]
 [ 4.3116045 ]]
<NDArray 2x1 @cpu(0)>

In [21]:
x[1:3, 1:2] = 5.0
x


[[ 4.03629494  3.50975561  3.04982066  4.03751945]
 [ 3.27015352  5.          9.          5.04082775]
 [ 3.54743147  5.          3.16326213  3.21169949]]
<NDArray 3x4 @cpu(0)>

# Broadcasting

In [23]:
x = nd.ones((3, 3))
print("x = ", x)
y = nd.arange(3)
print("y = ", y)

x + y

x =  
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 3x3 @cpu(0)>
y =  
[ 0.  1.  2.]
<NDArray 3 @cpu(0)>



[[ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]]
<NDArray 3x3 @cpu(0)>

In [26]:
y = y.reshape((3, 1))
y


[[ 0.]
 [ 1.]
 [ 2.]]
<NDArray 3x1 @cpu(0)>

In [27]:
x + y


[[ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]]
<NDArray 3x3 @cpu(0)>

# Converting from MXNet NDArray to NumPy

In [28]:
a = x.asnumpy()
type(a)

numpy.ndarray

In [29]:
y = nd.array(a)
y


[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 3x3 @cpu(0)>

# Managing context

Initializing an array on the first GPU

In [30]:
z = nd.ones(shape=(3, 3), ctx=mx.gpu(0))
z

MXNetError: [20:20:52] C:\projects\mxnet-distro-win\mxnet-build\src\imperative\imperative.cc:78: Operator _ones is not implemented for GPU.

Given an NDArray on a given context, we can copy it to another context by using the copyto() method.

In [31]:
x_gpu = x.copyto(mx.gpu(0))
x_gpu

MXNetError: [20:22:34] C:\projects\mxnet-distro-win\mxnet-build\src\ndarray\ndarray.cc:565: GPU is not enabled

If we ever want to check the context of an NDArray programmaticaly, we can just call its .context attribute.

In [32]:
print(x_gpu.context)

NameError: name 'x_gpu' is not defined

In [33]:
print(x.context)

cpu(0)


In order to perform an operation on two ndarrays x1 and x2, we need them both to live on the same context. And if they don’t already, we may need to explicitly copy data from one context to another. 
Imagine that your variable z already lives on your second GPU (gpu(0)). What happens if we call z.copyto(gpu(0))? It will make a copy and allocate new memory, even though that variable already lives on the desired device!

If two variables may already live on the same device, we only want to make a copy if the variables currently lives on different contexts. In these cases, we can call as_in_context(). If the variable is already the specified context then this is a no-op.

In [34]:
print('id(z): ', id(z))
z = z.copyto(mx.gpu(0))
print('id(z): ', id(z))
z = z.as_in_context(mx.gpu(0))
print('id(z): ', id(z))

NameError: name 'z' is not defined